#!/bin/bash
if [ -z $1 ]; then
echo "Please enter a react project name to proceed"
else
npx create-react-app $1
cd $1
mkdir src/actions; mkdir src/reducers; mkdir src/components; mkdir src/pages;
touch src/reducers/index.js; touch src/reducers/reducerExample.js; touch src/actions/index.js
npm install bootstrap
npm install react-router-dom@5
#routing in app.js
npm install axios
#import axios in the file u wanna fetch ur api
npm install redux react-redux
sed -i "5i import 'bootstrap/dist/css/bootstrap.css';\nimport { Provider } from 'react-redux';\nimport{ createStore } from 'redux';\nimport allReducers from './reducers/';" src/index.js
sed -i "13i <Provider store={store}>" src/index.js
sed -i "15i </Provider>" src/index.js 
sed -i "10i const store = createStore(\nallReducers,\nwindow.__REDUX_DEVTOOLS_EXTENSION__ &&window.__REDUX_DEVTOOLS_EXTENSION__()\n);" src/index.js
sed -i "2i import { BrowserRouter as Router, Switch, Route } from 'react-router-dom'" src/App.js
printf "export const actionExample = (parameterExample) => {  return {\ntype: 'ACTION',\npayload: parameterExample,};};" | tee -a src/actions/index.js
printf "const reducerExample = (state = 0, action) => {\nswitch (action.type) {\ncase 'ACTION':\nreturn state + 1;\ndefault:\nreturn state;}};\nexport default reducerExample;" | tee -a src/reducers/reducerExample.js
printf "import reducerExample from './reducerExample';\nimport { combineReducers } from 'redux';\nconst allReducers = combineReducers({reducerExample,});\nexport default allReducers;" | tee -a src/reducers/index.js
for ((i=0;i<=20;i++)); do
        if [ $i -eq 10 ]; then
        printf 'Scripted by Ahmed Khaled :D \n'
        else
        printf -- '- - - - - - - - - - - - - -\n'
        fi
done
printf "# React Project '$1' created.\n# Installed [Bootstrap / React Router / Axios / React Redux] Packages.\n# Added default project folders:\n  1.components: Add here any standalone component.\n  2.reducers: add all your reducer files there with same syntax of reducerExample and then add their names in src/reducers/index.js to make them visible to your redux store.\n  3.actions: add all your actions in src/actions/index.js with same syntax as the example and import it wherever you want.\n  4.pages: add here your main pages that goes in the src/App.js file.\n# Everything is imported and ready to use, all you need to import is your hooks to start! , and import axios in the file which you are going to use it.\n"
fi
